"""Exceptions"""

from . import base_api_models

OPERATION_DELETE = "DELETE"
OPERATION_ADD = "ADD"
OPERATION_UPDATE = "UPDATE"

ITEM_DELETED_SUCCESSFULLY_MESSAGE = "Item deleted successfully"
ITEM_ADDED_SUCCESSFULLY_MESSAGE = "Item added successfully"
ITEM_UPDATED_SUCCESSFULLY_MESSAGE = "Item updated successfully"

OK_STATUS = 200
CREATED_STATUS = 201

ITEM_DELETED_RESPONSE = base_api_models.APIResponse(
    code=OK_STATUS, type=OPERATION_DELETE, message=ITEM_DELETED_SUCCESSFULLY_MESSAGE
)

ITEM_ADDED_RESPONSE = base_api_models.APIResponse(
    code=CREATED_STATUS, type=OPERATION_ADD, message=ITEM_ADDED_SUCCESSFULLY_MESSAGE
)

ITEM_UPDATED_RESPONSE = base_api_models.APIResponse(
    code=OK_STATUS, type=OPERATION_UPDATE, message=ITEM_UPDATED_SUCCESSFULLY_MESSAGE
)
