"""Customer API constants"""

TAGS = ["customers"]

# Operation Ids
GET_CUSTOMERS_OPERATION_ID = "getCustomers"
GET_CUSTOMER_BY_ID_OPERATION_ID = "getCustomerById"
GET_CURRENT_CUSTOMER_OPERATION_ID = "getCurrentCustomer"
GET_OWN_APPOINTMENTS_OPERATION_ID = "getOwnAppointments"
CREATE_OWN_APPOINTMENT_OPERATION_ID = "createOwnAppointment"
GET_CUSTOMER_APPOINTMENTS_OPERATION_ID = "getCustomerAppointments"
GET_CUSTOMER_SERVICE_TURNS_OPERATION_ID = "getCustomerServiceTurns"
DELETE_CUSTOMER_BY_ID_OPERATION_ID = "deleteCustomerById"
ADD_CUSTOMER_OPERATION_ID = "addCustomer"
UPDATE_CUSTOMER_OPERATION_ID = "updateCustomer"
PATCH_CUSTOMER_OPERATION_ID = "patchCustomer"
